### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by baidefeng** [Dongyq815/VirRep#1]
When i run “python temp/VirRep/src/VirRep.py -i ~/virus3/seq/no_duplicates5_6.fasta -o temp/VirRep/vr -l 5000 -m temp/VirRep/src/model/VirRep.pth --use-amp --conservative --cpu-threads 8”. An error occurred as below, do you have ideals to fix it? Thanks.

Traceback (most recent call last):
  File "temp/VirRep/src/VirRep.py", line 283, in <module>
    pred_df = predict(
  File "/data5/baidefeng/virus3/temp/VirRep/src/predict.py", line 377, in predict
    headers_dict, seqlen_dict, scores_dict, positions_dict = score_segment(
  File "/data5/baidefeng/virus3/temp/VirRep/src/predict.py", line 27, in score_segment
    model = model.to(device)
  File "/data5/baidefeng/miniconda3/envs/vr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/data5/baidefeng/miniconda3/envs/vr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/data5/baidefeng/miniconda3/envs/vr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/data5/baidefeng/miniconda3/envs/vr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/data5/baidefeng/miniconda3/envs/vr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/data5/baidefeng/miniconda3/envs/vr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/data5/baidefeng/miniconda3/envs/vr/lib/python3.8/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by Dongyq815** [comment]
It seems that you have installed a CPU-only version of pytorch that does not support CUDA or the CUDA version is incompatible with the PyTorch version.  I would suggest to reinstall PyTorch following the instructions provided at https://pytorch.org/. Alternatively, if you intend to run in CPU mode, you need to add the --cpu option and remove the --use-amp option.

**Comment by 2061574124** [comment]
> It seems that you have installed a CPU-only version of pytorch that does not support CUDA or the CUDA version is incompatible with the PyTorch version. I would suggest to reinstall PyTorch following the instructions provided at https://pytorch.org/. Alternatively, if you intend to run in CPU mode, you need to add the --cpu option and remove the --use-amp option.

**(vr) dell@dell-PowerEdge-R720:~/bioinfo/virrep/VirRep$ python ./src/VirRep.py -i ./test/toy.fasta -o vr_out --conservative -w 2 --cpu-threads 8**
Traceback (most recent call last):
  File "/home/dell/bioinfo/virrep/VirRep/./src/VirRep.py", line 280, in <module>
    model = torch.load(options.model, map_location=torch.device('cpu'))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dell/miniconda3/envs/vr/lib/python3.12/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dell/miniconda3/envs/vr/lib/python3.12/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dell/miniconda3/envs/vr/lib/python3.12/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
**FileNotFoundError: [Errno 2] No such file or directory: 'model/VirRep.pth'**

**I'm very sorry, I also encountered an error. Please help to see how to fix. thank you**

**Comment by Dongyq815** [comment]
You need to enter the src directory and then run the command. Additionally, if you intend to run VirRep in CPU mode, you should add the --cpu option.

**Comment by baidefeng** [comment]
Thanks for your response. If we use --cpu option, time comsuming was so long. Do you have ideas to accelerate the process. Thank you.

**Comment by Dongyq815** [comment]
VirRep is designed to be executed on GPU. Its efficiency is significantly lower when run on CPU. I kindly suggest running VirRep on GPU whenever possible. If you need to use the --cpu option, running VirRep with more threads may improve efficiency.

> Thanks for your response. If we use --cpu option, time comsuming was so long. Do you have ideas to accelerate the process. Thank you.
